[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "sleep_sandbox"
version = "0.1.0"
description = "Sandbox for neuropixels sleep stage preprocessing and analysis"
requires-python = ">=3.10"

dependencies = [
    "spikewrap",          # brings spikeinterface with it
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "jupyter",
    "ipykernel",
    "pyyaml",             # for loading configs
    "python-dotenv",
    "spython",
    "kilosort",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sleep_sandbox*"]